version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - django

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: djnago
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - DEV_NAME=${DEV_NAME}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
      - PORT=${PORT}
      - USER=${USER}
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
    depends_on:
      - rabbitmq
      - celery_worker
      - redis

  redis:
    container_name: redis_service
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - .:/code

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7.14-management-alpine
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "15672"
    volumes:
      - .:/code

  celery_beat:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A config beat --loglevel=info"
    volumes:
      - .:/code
    environment:
      - DEV_NAME=${DEV_NAME}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
      - USER=${USER}
      - PORT=${PORT}
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
    depends_on:
      - rabbitmq

  celery_worker:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A config worker --loglevel=info"
    volumes:
    - .:/code
    environment:
      - DEV_NAME=${DEV_NAME}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
      - USER=${USER}
      - PORT=${PORT}
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
    depends_on:
      - rabbitmq

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - FLOWER_PORT=5555
    ports:
      - 5555:5555