# Generated by Django 3.2.10 on 2022-04-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='modified_at',
        ),
    ]
