# Generated by Django 3.2.10 on 2022-02-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='tid',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
