# Generated by Django 3.2.10 on 2022-02-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='approve',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='finish',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='ready',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
