# Generated by Django 3.2.10 on 2022-02-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='finish',
        ),
    ]
