# Generated by Django 3.2.10 on 2022-02-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('dev', 'dev'), ('service', 'service')], default='dev', max_length=10)),
                ('settings', models.TextField()),
                ('mappings', models.TextField()),
            ],
        ),
    ]
