# Generated by Django 3.2 on 2022-05-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('conveniences_store', models.CharField(db_index=True, max_length=30)),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('price', models.PositiveIntegerField(db_index=True, default=0)),
                ('category', models.CharField(db_index=True, max_length=20)),
                ('sale_type', models.CharField(choices=[('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('sale_product', 'sale_product'), ('present_product', 'present_product')], db_index=True, max_length=15)),
                ('image', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
