# Generated by Django 3.2 on 2022-05-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveniences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=20, null=True),
        ),
    ]
