# Generated by Django 3.2.10 on 2022-05-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conveniences', '0004_conveniencesstore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConveniencesStore',
            new_name='Store',
        ),
    ]
