# Generated by Django 3.2.10 on 2022-05-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveniences', '0005_rename_conveniencesstore_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
