# Generated by Django 3.2.10 on 2022-05-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveniences', '0006_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='month',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
