# Generated by Django 3.2.10 on 2022-05-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveniences', '0007_auto_20220508_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_off',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
