# Generated by Django 3.2.10 on 2022-05-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveniences', '0008_product_sale_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sale_type', models.CharField(choices=[('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1', '4+1'), ('할인상품', '할인상품'), ('증정상품', '증정상품')], db_index=True, max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
