# Generated by Django 3.2.10 on 2022-05-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveniences', '0009_saletype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleType',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_type',
            field=models.CharField(choices=[('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1', '4+1'), ('할인상품', '할인상품'), ('증정상품', '증정상품')], db_index=True, max_length=15),
        ),
    ]
