# Generated by Django 3.2.10 on 2022-05-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveniences', '0011_rename_conveniences_store_product_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='상품 종류', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default=None, help_text='상품 이미지', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='month',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='행사 월'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='상품 가격'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_off',
            field=models.BooleanField(db_index=True, default=False, help_text='행사 종료 날짜'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_type',
            field=models.CharField(choices=[('1+1', '1+1'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1', '4+1'), ('할인상품', '할인상품'), ('증정상품', '증정상품')], db_index=True, help_text='할인 타입', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.CharField(db_index=True, help_text='편의점 종류', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, help_text='상품 이름', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='행사 년'),
        ),
    ]
