name: remote ssh command
on:
  push:
    branches: [dev, master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
    - name: move directory
      run: |
        pwd
        cd /home/taxijjang/personal/django_shopping_mall_api_project

    - name: git checkout dev
      run: git checkout dev

    - name: git pull
      run: git pull origin dev

    - name: docker rebuilding
      run: docker-compose up --build -d