name: remote ssh command
on:
  push:
    branches: [dev, master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
    - name: Add env
      run: export DEV_NAME=shopping-mall-dev
#
#        script: |

#          export PASSWORD= ${{ secrets.PASSWORD }}
#          export HOST=${{ secrets.HOST }}
#          export PORT=${{ secrets.PORT }}
#          export DJANGO_SETTINGS_MODULE=config.settings.dev
#          export USER=${{ secrets.USERNAME }}
#
#          cd /home/taxijjang/personal/django_shopping_mall_api_project
#          git checkout dev
#          git pull origin dev
#          docker-compose up --build -d