name: remote ssh command
on:
  push:
    branches: [dev, master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/taxijjang/personal/django_shopping_mall_api_project
          git checkout dev
          git pull origin dev
          docker-compose up --build -d