name: remote ssh command
on:
  push:
    branches: 
      - dev
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME_NOT_ROOT }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd personal/django_shopping_mall_api_project
          git checkout dev
          git config user.name
          git config user.email
          docker-compose up -d --force-recreate --build
