# Generated by Django 3.2.10 on 2022-02-13 11:32

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, help_text='상품 이름', max_length=30)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, help_text='상품 가격', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='상품 이미지', null=True, upload_to=core.utils.rename_image_file_to_uuid)),
            ],
            options={
                'ordering': ['modified_at'],
            },
        ),
    ]
