# Generated by Django 3.2.10 on 2022-02-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220108_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ready',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='상품 가격', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, help_text='상품 이름', max_length=30),
        ),
    ]
