# Generated by Django 3.2.10 on 2022-02-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220213_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ready',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
