# Generated by Django 3.2.10 on 2022-02-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ready',
        ),
    ]
